retrieve_news_task:
  description: >
    Conduct a thorough reseach about {topic} by gathering the latest news articles,
  expected_output: >
    A list of 10 websites with the most relevant information about {topic}.
  agent : retrieve_news

website_scrape_task:
  description: >
    Scrape and extract information from the websites related to {topic}.

  expected_output: >
    Fully scrapped websites with all the information about {topic}.
  agent : web_scrapper

ai_news_write_task:
  description: >
    Write the news article to a file 
  expected_output: >
    Summarize   the information from the websites into a fully fledged news article in markdown format.
  agent : summarizer

file_write_task:
  description: >
    Write the news article to a file.
  expected_output: >
    A fully fledged  news article with all the information from the previous task into a file name news_article.md 
  agent : file_writer 